@api = http://localhost:3000/api/auth

### SIGNUP
POST {{api}}/signup
Content-Type: application/json

{
    "username":"Lora Willms",
    "email":"lora930@gmail.com",
    "password":"loraeyou",
    "roles":["admin","moderator"]
}

### SIGNIN
POST {{api}}/signin
Content-Type: application/json

{
    "email":"lora930@gmail.com",
    "password":"loraeyou"
}