### PRIMERO SE INSTALA LA EXTENSIÓN REST CLIENT

@api = http://localhost:3000/api/products

### GET
GET {{api}}

### POST
POST {{api}}
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYTI0YWFhMGYzZTRhMmY3MDM1ODMxZSIsImlhdCI6MTYwNDUxMTYzNCwiZXhwIjoxNjA0NTk4MDM0fQ.OKmE6tSmbsw6LOBRSXOVUqhuZPPk4qrBVXNthTpJWWQ

{
    "name": "Teclado 48er",
    "category": "technology",
    "price": 700,
    "imgUrl": "https://www.blueplanet-tec.com/wp-content/uploads/2019/12/teclado-gamer-rainbow.jpg"
}

### GET BY ID
@id = 5fa199d8cf51f922b0986d9d
GET {{api}}/{{id}}

### PUT 
PUT {{api}}/{{id}}
Content-Type: application/json

{
    "price":1500
}

### DELETE
@idelete = 5fa19cb29286420e6c1b4009
DELETE {{api}}/{{idelete}}
